#!/usr/bin/env python3
"""Gera README.md mestre a partir de data/hub.yaml."""
from pathlib import Path
from collections import defaultdict
import json
import yaml

ROOT = Path(__file__).resolve().parent.parent

CATEGORY_NAMES = {
    "provider-api": "📡 Provider APIs",
    "inference-provider": "🔌 Inference Providers",
    "subscription-plan": "💰 Subscription Plans",
    "inference-engine": "🛠️ Inference Engines (OSS)",
    "gateway": "🚪 Gateways / Routers",
    "specialty-api": "🎨 Specialty APIs",
    "agent-framework": "🤖 Agent Frameworks",
    "llm-framework": "📚 LLM Frameworks",
    "vector-db": "🗄️ Vector Databases",
    "eval-framework": "📊 Eval Frameworks",
    "model-catalog": "📦 Model Catalogs",
    "coding-tool": "💻 Coding Tools",
    "desktop-ui": "🖥️ Desktop UIs",
    "open-weights-family": "🧬 Open-Weights Families",
}

def fmt_pricing(p):
    if not p: return "—"
    m = p.get("model", "")
    if m == "free": return "🟢 Free"
    if m == "freemium": return "🟢 Freemium"
    if m == "subscription":
        u = p.get("monthly_usd")
        return f"💳 ${u}/mo" if u else "💳 Custom"
    if m == "pay-per-token":
        i, o = p.get("input_per_mtok_usd"), p.get("output_per_mtok_usd")
        if i and o: return f"💵 ${i}/${o} per MTok"
        return "💵 Pay-per-token"
    if m == "trial-credits":
        c = p.get("trial_credits_usd")
        return f"🎁 ${c} trial" if c else "🎁 Trial"
    if m == "self-hosted": return "🏠 Self-hosted"
    return m

def fmt_limits(r):
    if not r: return "—"
    parts = []
    if r.get("rpm"): parts.append(f"{r['rpm']} RPM")
    if r.get("rpd"): parts.append(f"{r['rpd']} RPD")
    if r.get("tpm"): parts.append(f"{r['tpm']} TPM")
    if r.get("monthly_tokens"):
        mt = r["monthly_tokens"]
        parts.append(f"{mt:,} tok/mo")
    return ", ".join(parts) if parts else "—"


def load_discovered():
    """Carrega data/discovered_models.json + enriquece com api_base do api_endpoints.yaml."""
    f = ROOT / "data/discovered_models.json"
    if not f.exists():
        return None
    try:
        data = json.loads(f.read_text())
    except Exception:
        return None

    # Enriquece com api_base do endpoints map
    endpoints_file = ROOT / "data/api_endpoints.yaml"
    if endpoints_file.exists():
        endpoints = yaml.safe_load(endpoints_file.read_text()) or {}
        for slug, result in data.items():
            if slug in endpoints and isinstance(endpoints[slug], dict):
                result["api_base"] = endpoints[slug].get("api_base", "—")
    return data


def fmt_discovered_section(discovered):
    """Renderiza a seção '🔍 Auto-discovered Models' a partir do snapshot."""
    if not discovered:
        return ""

    ok = [(s, r) for s, r in discovered.items() if r.get("status") == "ok" and r.get("count", 0) > 0]
    empty = [(s, r) for s, r in discovered.items() if r.get("status") == "ok" and r.get("count", 0) == 0]
    auth = [(s, r) for s, r in discovered.items() if "auth" in r.get("status", "")]
    errors = [(s, r) for s, r in discovered.items()
              if r.get("status") not in ("ok",) and "auth" not in r.get("status", "")]
    # Providers que respondem 200 mas com 0 modelos viram "empty_response"
    for slug, r in empty:
        errors.append((slug, {**r, "status": "empty_response (200 but no models)"}))

    total_models = sum(r.get("count", 0) for _, r in ok)

    lines = ["\n---\n"]
    lines.append("## 🔍 Auto-discovered Models\n")
    lines.append(
        f"> Auto-generated by `scripts/discover_models.py` probing public `/v1/models` endpoints. "
        f"**{len(ok)} providers** responding publicly, **{total_models} models** total.\n"
    )

    # Tabela principal: providers com /models público
    if ok:
        lines.append("### 🟢 Public endpoints (no auth required)\n")
        lines.append("| Provider | Models | Endpoint |")
        lines.append("|----------|------:|----------|")
        for slug, r in sorted(ok, key=lambda x: -x[1].get("count", 0)):
            count = r.get("count", 0)
            base = r.get("api_base", "—")
            lines.append(f"| `{slug}` | {count} | `{base}` |")
        lines.append("")

    # Auth-protected (collapsible)
    if auth:
        lines.append("<details>")
        lines.append(f"<summary>🔒 <strong>{len(auth)} providers require authentication</strong> (endpoint valid, key needed)</summary>\n")
        lines.append("| Provider | Status |")
        lines.append("|----------|--------|")
        for slug, r in sorted(auth):
            lines.append(f"| `{slug}` | {r.get('status')} |")
        lines.append("\n</details>\n")

    # Erros (collapsible)
    if errors:
        lines.append("<details>")
        lines.append(f"<summary>⚠️ <strong>{len(errors)} endpoints with errors</strong> (TODO: investigate)</summary>\n")
        lines.append("| Provider | Status |")
        lines.append("|----------|--------|")
        for slug, r in sorted(errors):
            lines.append(f"| `{slug}` | {r.get('status')} |")
        lines.append("\n</details>\n")

    return "\n".join(lines)


def main():
    hub = yaml.safe_load((ROOT / "data/hub.yaml").read_text())
    grouped = defaultdict(list)
    for e in hub:
        grouped[e["category"]].append(e)

    out = ["# 🌟 Free LLM Hub\n"]
    out.append("> A unified, community-driven catalog of LLM APIs, inference engines, gateways, and the entire OSS LLM ecosystem.\n")
    out.append(f"**Total entries:** {len(hub)} • **Last updated:** auto-generated\n")
    out.append("\n## 📑 Table of Contents\n")
    for cat in CATEGORY_NAMES:
        if cat in grouped:
            slug_anchor = CATEGORY_NAMES[cat].lower().replace(" ", "-").replace("/", "")
            out.append(f"- [{CATEGORY_NAMES[cat]}](#{slug_anchor}) ({len(grouped[cat])})")
    out.append("\n---\n")

    for cat, items in sorted(grouped.items(), key=lambda x: list(CATEGORY_NAMES).index(x[0]) if x[0] in CATEGORY_NAMES else 999):
        title = CATEGORY_NAMES.get(cat, cat)
        out.append(f"\n## {title}\n")

        # Subscription plans: ordena por preço
        if cat == "subscription-plan":
            items = sorted(items, key=lambda x: (x.get("pricing", {}) or {}).get("monthly_usd") or 999999)

        out.append("| Name | Country | Pricing | Rate Limits | Models / Notes | Link |")
        out.append("|------|:-:|:-:|:-:|------|:-:|")
        for e in items:
            name = e["name"]
            country = e.get("country", "—")
            pricing = fmt_pricing(e.get("pricing"))
            limits = fmt_limits(e.get("rate_limits"))
            models = ", ".join((e.get("models") or [])[:3]) or e.get("notes") or "—"
            if len(models) > 60: models = models[:57] + "..."
            link = f"[🔗]({e.get('website', e.get('github', '#'))})"
            out.append(f"| **{name}** | {country} | {pricing} | {limits} | {models} | {link} |")

    # Seção auto-gerada de modelos descobertos via /v1/models
    discovered = load_discovered()
    discovered_md = fmt_discovered_section(discovered)
    if discovered_md:
        out.append(discovered_md)

    out.append("\n---\n")
    out.append("## 🤝 Contributing\n")
    out.append("Edit `data/0X-*.yaml`, run `./scripts/merge.sh && python scripts/render_readme.py`, open a PR.\n")
    out.append("## 📜 License\nMIT\n")

    (ROOT / "README.md").write_text("\n".join(out))
    print(f"✅ README.md gerado com {len(hub)} entradas")

if __name__ == "__main__":
    main()
